# (c) Copyright 2019-2023 OLX
[package]
name = "libvips-bindings"
description = "Safe bindings for libvips"
version = "0.0.2"
authors = ["Augusto CeÃÅsar Dias <augusto.c.dias@gmail.com>"]
repository = "https://github.com/augustocdias/libvips-rust-bindings"
edition = "2018"

[build-dependencies]
bindgen = "0.64.0"
Inflector = "0.11"
cc = "1.0"
which = "4.4.0"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
