[package]
name = "libvips-bindings"
description = "Safe bindings for libvips"
version = "0.1"
authors = ["Augusto CeÌsar Dias <augusto.c.dias@gmail.com>"]
repository = "https://github.com/augustocdias/libvips-rust-bindings"
edition = "2018"

[build-dependencies]
bindgen = "0.53"
Inflector = "0.11"
cc = "1.0"
which = "3.1"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
